version: '3.8'

services:
  llm_service:
    build: ./llm_service
    ports:
      - "5001:5000"
    volumes:
      - ./llm_service/models:/app/models
      - ./llm_service/prompts:/app/prompts
    working_dir: /app
    command: python app.py
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ai_net

  ai_agent:
    build: ./ai_agent
    ports:
      - "5002:5002"
    depends_on:
      - llm_service
    working_dir: /app
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - ai_net

networks:
  ai_net:
    driver: bridge
